### ISSUE TITLE
[BUG] Doesn't work

### ISSUE THREAD

**Issue by alexmigf** [flixlix/energy-period-selector-plus#25]
**Describe the bug**
I have installed and added the card but doesn't show anything. I have wait days and nothing.

I wanted this to work so bad.

**Screenshots**

![Screenshot from 2023-10-27 20-08-56](https://github.com/flixlix/energy-period-selector-plus/assets/533273/65935141-65eb-4f83-9d73-b42e8d48ac0d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Browser: Firefox or Chrome
 - Version: latest

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-period-selector-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
Hi, what do you mean it doesn't work?
What have you tried? What did you expect to happen?
Help me help you :)

**Comment by alexmigf** [comment]
From what I understood you need to install the addon, create the card and wait. That's what I did.

**Comment by flixlix** [comment]
From your screenshot it seems like everything is working just fine. What am I missing?

**Comment by alexmigf** [comment]
The stats, if I select a date nothing happens.

**Comment by flixlix** [comment]
This card is only here to control the dates.
These dates are then consumed by any of these https://www.home-assistant.io/dashboards/energy/#energy-usage-graph or https://github.com/flixlix/energy-flow-card-plus placed in the same view.
Hope this helps

**Comment by alexmigf** [comment]
Oh, ok, didn't understood that, I will try later and see. Thanks!
