### ISSUE TITLE
[BUG] Empty buttons after install of Core 2023.11.0

### ISSUE THREAD

**Issue by rrozema** [flixlix/energy-period-selector-plus#26]
**Describe the bug**
The buttons for "DAY", "WEEK", "MONTH" and "YEAR" no longer show any text after the upgrade to Core 2023.11.0. Only "CUSTOM" still has text in it, the rest are empty boxes.

**To Reproduce**
1. install Core 2023.11.0
2. Go to a page that has the energy-period-selector-plus card on it

**Expected behavior**
Buttons should still show their text. 

**Screenshots**
![image](https://github.com/flixlix/energy-period-selector-plus/assets/1747982/f79f404a-e8d3-4f25-8cb1-9205269ee50b)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 118.0.5993.118

**Smartphone (please complete the following information):**
 - Device: Xiaomi MI 11
 - OS: android 
 - Browser: chrome
 - Version: 

**Additional context**
Before Core 2023.11.0 the text was shown and no other changes were made to my installation or the pages having epsp. Core 2023.11.0 introduces its own new energy selector, so can it be the icons that were previously used were removed from HA? [https://www.home-assistant.io/blog/2023/11/01/release-202311/#select-any-date-range-in-the-energy-dashboard](https://www.home-assistant.io/blog/2023/11/01/release-202311/#select-any-date-range-in-the-energy-dashboard)

I like the energy selector plus's looks and behavior better than the new standard behavior. For example the new standard selector still selects data for the entire month, even when I select only the last few days of that month as the start of the custom date range and the end of the custom period is months away: January still shows a high value for the entire months, even though I selected a custom period from January 27th till today.

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-period-selector-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
Thanks for pointing this out. I fixed it in #27.
Just released version 0.2.3 🥳

**Comment by rrozema** [comment]
Works like a charm. Thank you.

Op vr 3 nov. 2023 09:24 schreef Luca Félix ***@***.***>:
