### ISSUE TITLE
[FEATURE REQUEST] One line mode

### ISSUE THREAD

**Issue by MattJeanes** [flixlix/energy-period-selector-plus#8]
**Is your feature request related to a problem? Please describe.**

There is a lot of wasted vertical space when using this resource as a header

**Describe the solution you'd like**

I would like to see an option to put everything on one line, instead of split across 2

**Describe alternatives you've considered**

N/A

**Additional context**

Here is a quick mockup I did by editing the CSS in the browser

![image](https://github.com/flixlix/energy-period-selector-plus/assets/2363642/b4635307-c1f5-49f7-a2fb-6fe7a0af3bf6)

Nice work by the way, I've been looking for something like this for a while!

**Comment by flixlix** [comment]
Created on line mode in case card has enough horizontal space. Will be available in version 0.2.1 🥳

**Comment by MattJeanes** [comment]
Amazing! Thank you so much, and so quickly as well! 🙌🏻 🥳

**Comment by guevara777** [comment]
Would love to see that. Thank you! When will the version 0.2.1 be released?

**Comment by flixlix** [comment]
Sorry, forgot to make the release. This feature should now be available in 0.2.1. Unfortunately, as of HA version 2023.06, this card is unfortunately broken (see #11). I'm actively debugging the issue and trying to fix it as soon as possible

**Comment by MattJeanes** [comment]
So it's not just me! I've found refreshing the page shows the card data properly but it is annoying 😕

**Comment by flixlix** [comment]
Hey @MattJeanes,
sorry for the inconvenience. This was definitely difficult to debug, but I fixed the bug in version 0.2.2 😅
